baseURL = "https://www.greatdayofthelord.org/"
languageCode = "en-us"
title = "Great Day of the Lord"
theme = "ananke"
assetsDir = "assets"
googleAnalytics = "UA-141901513-1"

[params]
  description = "Exploring the order of the signs of the Second Coming of Jesus Christ."
  background_color_class = "bg-brown"
  images = ["/img/signs.png"]
