[build]
publish = "public"
command = "npm run build:prod"
HUGO_VERSION = "0.55.6"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "npm run build:preview"

[context.branch-deploy]
command = "npm run build:preview"
